System Stability
pdq/PowerShell-Scanners pull request #16
Opened 2020-05-07 06:26 UTC by BenGibb

Collects System Stability statistics from Win32_ReliabilityStabilityMetrics and returns:

- Minimum stability over the collected period
- Average stability over the collected period
- Maximum stability over the collected period
- The last generated Stability Index
- Date and time of the last generated Stability Index

2020-05-12 22:01 UTC, PDQDakota requested changes
Thanks for this, the reliability monitor is really neat!

2020-05-12 22:01 UTC, PDQDakota commented on PowerShell Scanners/System Stability/System Stability.ps1
> +$StabilityMetrcs = Get-WmiObject -ClassName Win32_ReliabilityStabilityMetrics | Select-Object -First $Count
Could you swap out `Get-WmiObject` for `Get-CimInstance`? The new Cim cmdlet will get the same info a little bit faster here.

2020-05-13 00:27 UTC, BenGibb commented on PowerShell Scanners/System Stability/System Stability.ps1
> +$StabilityMetrcs = Get-WmiObject -ClassName Win32_ReliabilityStabilityMetrics | Select-Object -First $Count
I've made the changes on my end (also fixed/cleaned up the TimeGenerated as a side effect)
How do I get the changes to you?
(still rather green when it comes to Git)

2020-05-13 14:21 UTC, PDQDakota commented on PowerShell Scanners/System Stability/System Stability.ps1
> +$StabilityMetrcs = Get-WmiObject -ClassName Win32_ReliabilityStabilityMetrics | Select-Object -First $Count
A push from the same branch (which you've already done!) will get the updates to us.

2020-05-13 14:22 UTC, PDQDakota approved these changes
Thank you for helping out!

2020-05-24 19:26 UTC, Colby-PDQ approved these changes

2020-05-24 19:26 UTC, merged