RSOP (Basic GPO Info)
pdq/PowerShell-Scanners pull request #21
Opened 2020-06-17 19:02 UTC by ryanjoachim

Bare minimum GPO information needed to be useful.

2020-06-18 15:46 UTC, PDQDakota submitted a review, later dismissed

2020-06-22 20:03 UTC, Colby-PDQ requested changes

2020-06-22 20:03 UTC, Colby-PDQ commented on PowerShell Scanners/RSOP (Basic GPO Info)/Readme.md
> +Returns the following:
This won't format properly. Markdown requires either 2 spaces at the end of the previous line, or an empty line. https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#paragraphs

2020-06-22 20:03 UTC, Colby-PDQ commented on PowerShell Scanners/RSOP (Basic GPO Info)/Readme.md
> +* filterAllowed (Is the target restricted from applying the GPO)
`filterAllowed` should be `FilterAllowed`, to match the output of the script.

2020-06-22 20:03 UTC, Colby-PDQ commented on PowerShell Scanners/RSOP (Basic GPO Info)/Scan Profile.xml
> +        <Name>RSPO (Basic GPO Info)</Name>
`RSPO` should be `RSOP`.

2020-06-22 20:03 UTC, Colby-PDQ commented on PowerShell Scanners/RSOP (Basic GPO Info)/Scan Profile.xml
> +    <Name>PS - RSOP (Basic GPO Info)</Name>
I recommend changing `Info` to `Information`, to match everything else.

2020-06-23 16:42 UTC, ryanjoachim reviewed
Changes (hopefully) made.

2020-06-24 13:04 UTC, Colby-PDQ approved these changes

2020-06-24 13:04 UTC, merged